package queue

fun main() {
    val queue = FixedQueue<Int>(4)
    queue.apply {
        debug()
        enqueue(1)
        enqueue(2)
        enqueue(3)
        enqueue(4)
        enqueue(5)
        debug()
        dequeue()
        debug()
        enqueue(5)
        enqueue(6)
        debug()
        dequeue()
        dequeue()
        dequeue()
        dequeue()
        debug()
        enqueue(1)
        enqueue(2)
        enqueue(3)
        enqueue(4)
        debug()
        dequeue()
        dequeue()
        enqueue(5)
        enqueue(6)
        debug()
        dequeue()
        enqueue(7)
        debug()
        println(full())
        dequeue()
        dequeue()
        enqueue(8)
        debug()
        dequeue()
        dequeue()
        dequeue()
        debug()
        println(empty())
        println(full())
    }
}